version: 0.0
os: linux
files:
  - source: /
    destination: ~/deploy/discord-bot
hooks:
  ApplicationStart:
    - location: ~/deploy/discord-bot/aws/start_bot.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ~/deploy/discord-bot/aws/stop_bot.sh
      timeout: 300
      runas: root
